# Generated by Django 5.1.6 on 2025-03-06 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=30)),
                ('phoneno', models.IntegerField()),
                ('department', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='')),
                ('doctorusername', models.CharField(max_length=30)),
                ('doctorpassword', models.CharField(max_length=30)),
                ('role', models.CharField(default='doctor', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='add_treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentname', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='contact1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.sign_up')),
            ],
        ),
        migrations.CreateModel(
            name='appointment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=50)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('appointment_doctor_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.add_doctor')),
                ('appointment_user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.sign_up')),
            ],
        ),
    ]
