# Generated by Django 5.1.6 on 2025-03-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_appointment1_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment1',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
