# Generated by Django 5.1.6 on 2025-03-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_appointment1_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment1',
            name='appointment_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
